[package]
name = "rosenbrock_test"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
wrenfold-traits = { version = "0.0.6", features = ["nalgebra"] }
nalgebra = { version = "0.32" }

[workspace]
