[package]
name = "wrenfold-test-utils"
version.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[dependencies]
nalgebra = { workspace = true }

[dev-dependencies]
approx = { workspace = true }
