[package]
name = "custom_types_rust_test"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
wrenfold-test-utils = { workspace = true }
wrenfold-traits = { workspace = true }
nalgebra = { workspace = true }

[dev-dependencies]
approx = { workspace = true }
