{% set version = "0.1.1" %}

package:
  name: wrenfold
  version: {{ version }}

source:
  path: ../../..

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python >=3.9
    - scikit-build-core ==0.9.8
    - cmake >=3.20
    - ninja >=1.5
    - mypy ==1.9.0
    - pip
  run:
    - python

test:
  imports:
    - wrenfold
    - wrenfold.sym
  requires:
    - pip
    - numpy
    - sympy
    - jax
  source_files:
    - components/wrapper/tests/*.py
    - examples/**/*.py
    - support/test_wheel.py
  commands:
    - pip check
    - python support/test_wheel.py

about:
  home: https://github.com/wrenfold/wrenfold
  summary: Toolkit for generating code from symbolic math expressions.
  license: MIT
  license_file:
    - LICENSE
    - dependencies/abseil-cpp/LICENSE
    - dependencies/fmt/LICENSE
    - dependencies/pybind11/LICENSE
  doc_url: https://wrenfold.org

extra:
  recipe-maintainers:
    - gareth-cross
