"""Symbolic code-generation tools."""

# ruff: noqa: F401

from pywrenfold import __version__ as __version__

__author__ = "Gareth <gcross.code@icloud.com>"
__copyright__ = "Copyright (C) 2024 Gareth Cross"
__license__ = "MIT"


from .code_generation import (
    BaseGenerator as BaseGenerator,
    CodegenFuncInvocationResult as CodegenFuncInvocationResult,
    CppGenerator as CppGenerator,
    CppMatrixTypeBehavior as CppMatrixTypeBehavior,
    FunctionDescription as FunctionDescription,
    OptimizationParams as OptimizationParams,
    OutputArg as OutputArg,
    PythonGenerator as PythonGenerator,
    PythonGeneratorFloatWidth as PythonGeneratorFloatWidth,
    PythonGeneratorTarget as PythonGeneratorTarget,
    ReturnValue as ReturnValue,
    ReturnValueOrOutputArg as ReturnValueOrOutputArg,
    RustGenerator as RustGenerator,
    create_function_description as create_function_description,
    cse_function_description as cse_function_description,
    generate_function as generate_function,
    generate_python as generate_python,
    mkdir_and_write_file as mkdir_and_write_file,
    transpile as transpile,
)
from .enumerations import (
    NumberSet as NumberSet,
    RelationalOperation as RelationalOperation,
    StdMathFunction as StdMathFunction,
    SymbolicConstant as SymbolicConstant,
)
from .type_annotations import (
    FloatScalar as FloatScalar,
    IntScalar as IntScalar,
    Matrix1 as Matrix1,
    Matrix1x2 as Matrix1x2,
    Matrix1x3 as Matrix1x3,
    Matrix1x4 as Matrix1x4,
    Matrix1x5 as Matrix1x5,
    Matrix1x6 as Matrix1x6,
    Matrix1x7 as Matrix1x7,
    Matrix1x8 as Matrix1x8,
    Matrix1x9 as Matrix1x9,
    Matrix2 as Matrix2,
    Matrix2x3 as Matrix2x3,
    Matrix2x4 as Matrix2x4,
    Matrix2x5 as Matrix2x5,
    Matrix2x6 as Matrix2x6,
    Matrix2x7 as Matrix2x7,
    Matrix2x8 as Matrix2x8,
    Matrix2x9 as Matrix2x9,
    Matrix3 as Matrix3,
    Matrix3x2 as Matrix3x2,
    Matrix3x4 as Matrix3x4,
    Matrix3x5 as Matrix3x5,
    Matrix3x6 as Matrix3x6,
    Matrix3x7 as Matrix3x7,
    Matrix3x8 as Matrix3x8,
    Matrix3x9 as Matrix3x9,
    Matrix4 as Matrix4,
    Matrix4x2 as Matrix4x2,
    Matrix4x3 as Matrix4x3,
    Matrix4x5 as Matrix4x5,
    Matrix4x6 as Matrix4x6,
    Matrix4x7 as Matrix4x7,
    Matrix4x8 as Matrix4x8,
    Matrix4x9 as Matrix4x9,
    Matrix5 as Matrix5,
    Matrix5x2 as Matrix5x2,
    Matrix5x3 as Matrix5x3,
    Matrix5x4 as Matrix5x4,
    Matrix5x6 as Matrix5x6,
    Matrix5x7 as Matrix5x7,
    Matrix5x8 as Matrix5x8,
    Matrix5x9 as Matrix5x9,
    Matrix6 as Matrix6,
    Matrix6x2 as Matrix6x2,
    Matrix6x3 as Matrix6x3,
    Matrix6x4 as Matrix6x4,
    Matrix6x5 as Matrix6x5,
    Matrix6x7 as Matrix6x7,
    Matrix6x8 as Matrix6x8,
    Matrix6x9 as Matrix6x9,
    Matrix7 as Matrix7,
    Matrix7x2 as Matrix7x2,
    Matrix7x3 as Matrix7x3,
    Matrix7x4 as Matrix7x4,
    Matrix7x5 as Matrix7x5,
    Matrix7x6 as Matrix7x6,
    Matrix7x8 as Matrix7x8,
    Matrix7x9 as Matrix7x9,
    Matrix8 as Matrix8,
    Matrix8x2 as Matrix8x2,
    Matrix8x3 as Matrix8x3,
    Matrix8x4 as Matrix8x4,
    Matrix8x5 as Matrix8x5,
    Matrix8x6 as Matrix8x6,
    Matrix8x7 as Matrix8x7,
    Matrix8x9 as Matrix8x9,
    Matrix9 as Matrix9,
    Matrix9x2 as Matrix9x2,
    Matrix9x3 as Matrix9x3,
    Matrix9x4 as Matrix9x4,
    Matrix9x5 as Matrix9x5,
    Matrix9x6 as Matrix9x6,
    Matrix9x7 as Matrix9x7,
    Matrix9x8 as Matrix9x8,
    Opaque as Opaque,
    Shape as Shape,
    Vector1 as Vector1,
    Vector2 as Vector2,
    Vector3 as Vector3,
    Vector4 as Vector4,
    Vector5 as Vector5,
    Vector6 as Vector6,
    Vector7 as Vector7,
    Vector8 as Vector8,
    Vector9 as Vector9,
)
