"""Symbolic code-generation tools."""

# ruff: noqa: F401

from pywrenfold import __version__

__author__ = "Gareth <gcross.code@icloud.com>"
__copyright__ = "Copyright (C) 2024 Gareth Cross"
__license__ = "MIT"


from .code_generation import (
    BaseGenerator,
    CodegenFuncInvocationResult,
    CppGenerator,
    CppMatrixTypeBehavior,
    FunctionDescription,
    OptimizationParams,
    OutputArg,
    PythonGenerator,
    PythonGeneratorFloatWidth,
    PythonGeneratorTarget,
    ReturnValue,
    ReturnValueOrOutputArg,
    RustGenerator,
    create_function_description,
    cse_function_description,
    generate_function,
    generate_python,
    mkdir_and_write_file,
    transpile,
)
from .enumerations import NumberSet, RelationalOperation, StdMathFunction, SymbolicConstant
from .type_annotations import (
    FloatScalar,
    IntScalar,
    Matrix1,
    Matrix1x2,
    Matrix1x3,
    Matrix1x4,
    Matrix1x5,
    Matrix1x6,
    Matrix1x7,
    Matrix1x8,
    Matrix1x9,
    Matrix2,
    Matrix2x3,
    Matrix2x4,
    Matrix2x5,
    Matrix2x6,
    Matrix2x7,
    Matrix2x8,
    Matrix2x9,
    Matrix3,
    Matrix3x2,
    Matrix3x4,
    Matrix3x5,
    Matrix3x6,
    Matrix3x7,
    Matrix3x8,
    Matrix3x9,
    Matrix4,
    Matrix4x2,
    Matrix4x3,
    Matrix4x5,
    Matrix4x6,
    Matrix4x7,
    Matrix4x8,
    Matrix4x9,
    Matrix5,
    Matrix5x2,
    Matrix5x3,
    Matrix5x4,
    Matrix5x6,
    Matrix5x7,
    Matrix5x8,
    Matrix5x9,
    Matrix6,
    Matrix6x2,
    Matrix6x3,
    Matrix6x4,
    Matrix6x5,
    Matrix6x7,
    Matrix6x8,
    Matrix6x9,
    Matrix7,
    Matrix7x2,
    Matrix7x3,
    Matrix7x4,
    Matrix7x5,
    Matrix7x6,
    Matrix7x8,
    Matrix7x9,
    Matrix8,
    Matrix8x2,
    Matrix8x3,
    Matrix8x4,
    Matrix8x5,
    Matrix8x6,
    Matrix8x7,
    Matrix8x9,
    Matrix9,
    Matrix9x2,
    Matrix9x3,
    Matrix9x4,
    Matrix9x5,
    Matrix9x6,
    Matrix9x7,
    Matrix9x8,
    Opaque,
    Shape,
    Vector1,
    Vector2,
    Vector3,
    Vector4,
    Vector5,
    Vector6,
    Vector7,
    Vector8,
    Vector9,
)
