[package]
name = "rust-codegen-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
zen-traits = { path = "../zen-traits", version = "0.0.1", features = ["nalgebra"] }
nalgebra = { version = "0.32.3" }

[dev-dependencies]
approx = { version = "0.5.1" }
