class ArithmeticError(Exception): ...

class AssertionError(Exception): ...

class DimensionError(Exception): ...

class DomainError(Exception): ...

class InvalidArgumentError(Exception): ...

class TypeError(Exception): ...
