import pywrenfold.enumerations
import pywrenfold.sym

class Variable:
    def __init__(self, name: str, number_set: pywrenfold.enumerations.NumberSet = ...) -> None: ...
    def is_identical_to(self, other: Variable) -> bool: ...
    def to_expression(self) -> pywrenfold.sym.Expr: ...
    def __eq__(self, other: Variable) -> bool: ...
    def __hash__(self) -> int: ...
    @property
    def is_unique_variable(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def set(self) -> pywrenfold.enumerations.NumberSet: ...
