import pywrenfold.sym
import pywrenfold.type_info
from typing import overload

def function_argument_variable(arg_index: int, element_index: int, type: pywrenfold.type_info.NumericType) -> pywrenfold.sym.Expr: ...
@overload
def to_sympy(expr: pywrenfold.sym.Expr, sp: object | None = ..., evaluate: bool = ...) -> object: ...
@overload
def to_sympy(expr: pywrenfold.sym.BooleanExpr, sp: object | None = ..., evaluate: bool = ...) -> object: ...
@overload
def to_sympy(expr: pywrenfold.sym.MatrixExpr, sp: object | None = ..., evaluate: bool = ...) -> object: ...
