[package]
name = "bspline_rust_test"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
wrenfold-traits = { workspace = true }
nalgebra = { workspace = true }

[dev-dependencies]
approx = { workspace = true }
