"""
Script that generates the `python_api_docs.rst` file.
"""

import argparse
import inspect
import typing
from pathlib import Path

# The built library needs to be on the import path by this point.
from wrenfold import (
    ast,
    code_generation,
    enumerations,
    exceptions,
    external_functions,
    geometry,
    sym,
    sympy_conversion,
    type_annotations,
    type_info,
)

DOCS_DIR = Path(__file__).parent.absolute()


def generate_rst_for_module(module: typing.Any, module_name: str, output_dir: Path):
    """
    Write out rst files for classes + functions in the provided module.
    """
    functions: list[str] = []
    classes: list[tuple[str, list[str]]] = []
    data: list[tuple[str, str | None]] = []
    type_unions: list[tuple[str, str]] = []
    for member_name in sorted(dir(module)):
        if member_name.startswith("_"):
            continue

        member = getattr(module, member_name)
        if inspect.ismodule(member):
            continue
        if member.__doc__ is not None and "OMIT_FROM_SPHINX" in member.__doc__:
            continue

        if inspect.isclass(member):
            class_static_functions = []
            for child_member_name in sorted(dir(member)):
                child_member = getattr(member, child_member_name)
                if "nanobind.nb_func" in str(child_member):
                    class_static_functions.append(child_member_name)

            classes.append((member_name, class_static_functions))

        elif inspect.isbuiltin(member) or inspect.isfunction(member) or callable(member):
            to_string = str(member)
            if to_string == "typing.Annotated":
                continue
            elif to_string.startswith("typing.Annotated"):
                metadata = getattr(member, "__metadata__", [])
                if len(metadata) and isinstance(metadata[-1], str):
                    data.append((member_name, metadata[-1]))
                else:
                    data.append((member_name, "Annotation is missing a docstring."))
            else:
                functions.append(member_name)
        elif isinstance(member, (sym.Expr, sym.BooleanExpr)):
            # Some custom handling for constants that have incorrect __doc__ values.
            if isinstance(member, sym.Expr) and member.is_identical_to(sym.I):
                custom_str = "The imaginary constant. Used to denote complex numbers."
            elif isinstance(member, sym.Expr) and member.is_identical_to(sym.pi):
                custom_str = "Pi"
            elif isinstance(member, sym.Expr) and member.is_identical_to(sym.E):
                custom_str = "Euler's constant."
            elif isinstance(member, sym.Expr) and member.is_identical_to(sym.zoo):
                custom_str = "Complex infinity. One of the poles of the Riemann sphere."
            elif isinstance(member, sym.Expr) and member.is_identical_to(sym.nan):
                custom_str = "Used to represent mathematically undefined expressions."
            elif isinstance(member, sym.BooleanExpr) and member.is_identical_to(sym.true):
                custom_str = "Boolean true."
            elif isinstance(member, sym.BooleanExpr) and member.is_identical_to(sym.false):
                custom_str = "Boolean false."
            else:
                custom_str = None
            data.append((member_name, custom_str))
        elif typing.get_origin(member) is typing.Union:
            type_unions.append((member_name, str(member)))

    parts = [f"{module_name}\n{'=' * len(module_name)}"]

    for tu_name, tu_annotation in type_unions:
        parts.extend([f".. py:data:: wrenfold.{module_name}.{tu_name}", f"  ``{tu_annotation}``"])

    for d, override_str in data:
        if override_str is None:
            parts.append(f".. autodata:: wrenfold.{module_name}.{d}")
        else:
            parts.extend([f".. py:data:: wrenfold.{module_name}.{d}", f"  {override_str}"])

    parts.extend(f".. autofunction:: wrenfold.{module_name}.{func}" for func in functions)

    # Based on: https://github.com/wjakob/nanobind/discussions/707
    for klass, class_static_functions in classes:
        excluded_members = ["__dict__", "__weakref__", "__repr__", "__getstate__", "__setstate__"]
        excluded_members += class_static_functions
        class_directives = "\n  ".join(
            [
                ":members:",
                ":special-members:",
                f":exclude-members: {','.join(excluded_members)}",
            ]
        )
        directive = f".. autoclass:: wrenfold.{module_name}.{klass}\n  {class_directives}"
        for func_name in class_static_functions:
            directive += f"\n\n  .. automethod:: {func_name}"
        parts.append(directive)

    contents = f".. Machine generated by {Path(__file__).name}. Do not edit by hand.\n\n"
    contents += "\n\n".join(parts)
    contents += "\n"

    output_path = output_dir / f"{module_name}.rst"
    with open(output_path, "wb") as handle:
        handle.write(contents.encode("utf-8"))


def main(args: argparse.Namespace):
    output_dir = Path(args.output_dir)

    generate_rst_for_module(module=sym, module_name="sym", output_dir=output_dir)
    generate_rst_for_module(module=geometry, module_name="geometry", output_dir=output_dir)
    generate_rst_for_module(module=ast, module_name="ast", output_dir=output_dir)
    generate_rst_for_module(
        module=code_generation, module_name="code_generation", output_dir=output_dir
    )
    generate_rst_for_module(
        module=sympy_conversion, module_name="sympy_conversion", output_dir=output_dir
    )
    generate_rst_for_module(
        module=type_annotations, module_name="type_annotations", output_dir=output_dir
    )
    generate_rst_for_module(module=enumerations, module_name="enumerations", output_dir=output_dir)
    generate_rst_for_module(module=exceptions, module_name="exceptions", output_dir=output_dir)
    generate_rst_for_module(module=type_info, module_name="type_info", output_dir=output_dir)
    generate_rst_for_module(
        module=external_functions,
        module_name="external_functions",
        output_dir=output_dir,
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output_dir",
        type=str,
        help="Output directory write the RST file into.",
        default=str(DOCS_DIR / "source" / "python_api"),
    )
    return parser.parse_args()


if __name__ == "__main__":
    main(parse_args())
